sudo: required

before_install:
  - curl https://package.perforce.com/perforce.pubkey | sudo apt-key add -
  - echo "deb http://package.perforce.com/apt/ubuntu/ precise release" | sudo tee -a /etc/apt/sources.list
  - sudo apt-add-repository ppa:fish-shell/release-2 -y
  - sudo apt-get update -qq

install:
  - sudo apt-get install helix-cli
  - sudo apt-get install zsh
  - sudo apt-get install fish

before_script:
  - sudo ./install.sh

script:
  - ./test.sh
